name = "Alphafold2"
uuid = "0c8f8c2f-a7ca-4708-bf8a-16d94ee6c3d0"
authors = ["Ben Murrell"]
version = "0.1.0"

[deps]
BatchedTransformations = "8ba27c4b-52b5-4b10-bc66-a4fda05aa11b"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Onion = "fdebf6c2-71da-43a1-b539-c3bc3e09c5c6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BatchedTransformations = "0.3"
ChainRulesCore = "1"
NNlib = "0.9"
NPZ = "0.4"
Onion = "0.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
